'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function ui(){const html=fs.readFileSync(require('node:path').join(__dirname,'../games/phantom_manor.html'),'utf8'),events={},els=new Map(),noop=()=>{};let frames=0;
const drawing=new Proxy({}, {get:(_,k)=>k==='createRadialGradient'?()=>({addColorStop:noop}):noop,set:()=>true});
function el(id){if(!els.has(id)){const classes=new Set();els.set(id,{id,hidden:false,textContent:'',dataset:{},style:{},innerHTML:'',classList:{toggle(k,v){v=v===undefined?!classes.has(k):v;v?classes.add(k):classes.delete(k);return v;},contains:k=>classes.has(k)},setAttribute(k,v){this[k]=v;},focus(){},getContext:()=>drawing,querySelector:()=>null,addEventListener:noop});}return els.get(id);}
const doc={getElementById:el,documentElement:el('root'),hidden:false,activeElement:null,fullscreenElement:null,addEventListener:(n,fn)=>events[n]=fn};
const window={addEventListener:noop,matchMedia:()=>({matches:false})};const c={window,document:doc,console,requestAnimationFrame(){frames++;}};
for(const s of html.matchAll(/<script id="manor-[^"]+">([\s\S]*?)<\/script>/g))vm.runInNewContext(s[1],c);
return {window,doc,el,events,frames:()=>frames,click(action){events.click({target:{closest:()=>({dataset:{action}})}});}};}
test('large view toggles independently of game state; fullscreen denial remains usable',async()=>{const u=ui(),g=u.window.PhantomManor;u.click('start');const before=g.getState();u.click('large');assert.equal(u.doc.documentElement.classList.contains('large-view'),true);assert.equal(u.el('large')['aria-pressed'],'true');assert.deepEqual(g.getState(),before);u.click('large');assert.equal(u.doc.documentElement.classList.contains('large-view'),false);u.doc.documentElement.requestFullscreen=()=>Promise.reject(Error('denied'));u.click('fullscreen');await new Promise(r=>setImmediate(r));assert.match(u.el('view-status').textContent,/unavailable/i);assert.equal(u.doc.documentElement.classList.contains('large-view'),false);u.doc.fullscreenElement=u.doc.documentElement;u.events.fullscreenchange();assert.equal(u.el('fullscreen').textContent,'Exit fullscreen');u.doc.fullscreenElement=null;u.events.fullscreenchange();assert.equal(u.el('fullscreen').textContent,'Fullscreen');assert.equal(u.frames(),1);});
test('global M works while an audio slider is focused',async()=>{const u=ui();u.events.keydown({code:'KeyM',target:{tagName:'INPUT'},repeat:false});await new Promise(r=>setImmediate(r));assert.equal(u.el('sound').textContent,'Sound unavailable');});
test('UI audio gracefully reports unavailable without changing gameplay',async()=>{const u=ui();u.click('start');u.click('sound');await new Promise(r=>setImmediate(r));assert.equal(u.el('sound').textContent,'Sound unavailable');assert.equal(u.window.PhantomManor.getState().mode,'playing');assert.equal(u.window.PhantomManorAudio.status().on,false);});
