'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=()=>fs.readFileSync(require('node:path').join(__dirname,'../games/phantom_manor.html'),'utf8');
function factory(){const script=html().match(/<script id="manor-audio">([\s\S]*?)<\/script>/);assert.ok(script,'sequenced audio module exists');const window={};vm.runInNewContext(script[1],{window});return window.createManorAudio;}
function fake(){const starts=[],nodes=[];const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});const ac={currentTime:0,state:'suspended',destination:{},resume(){this.state='running';return Promise.resolve();},suspend(){this.state='suspended';return Promise.resolve();},createGain(){return {gain:param(),connect(){},disconnect(){}};},createOscillator(){const o={frequency:param(),connect(){},disconnect(){},start(t){starts.push(t);},stop(){}};nodes.push(o);return o;}};return {ac,starts,nodes};}
test('opt-in sequence schedules melody and accompaniment on audio time, then silence when muted or paused',async()=>{const {ac,starts}=fake(),a=factory()(()=>ac);a.tick('foyer');assert.equal(starts.length,0);await a.enable(true);a.tick('foyer');assert.ok(starts.length>=5);assert.ok(starts.every(t=>t>=ac.currentTime));const count=starts.length;a.tick('foyer');assert.equal(starts.length,count,'one scheduler, no duplicated same beat');await a.enable(false);ac.currentTime+=10;a.tick('foyer');assert.equal(starts.length,count);await a.enable(true);a.setPaused(true);ac.currentTime+=10;a.tick('foyer');assert.equal(starts.length,count);assert.equal(ac.state,'suspended');});
test('effects use distinct bounded voices, independent volumes, unsupported audio is safe',async()=>{const {ac,starts,nodes}=fake(),a=factory()(()=>ac);await a.enable(true);a.setVolume('music',0);a.tick('library');assert.equal(starts.length,0);a.effect('door');const count=starts.length;assert.ok(count>0);a.setVolume('effects',0);a.effect('door');assert.equal(starts.length,count);a.setVolume('effects',1);for(let i=0;i<100;i++)a.effect('ending');assert.ok(a.status().voices<=48);await a.enable(false);assert.equal(a.status().voices,0);a.effect('page');assert.equal(starts.length,nodes.length);assert.equal(await factory()(()=>null).enable(true),false);});
test('late resume cannot override mute or pause, and ended voices disconnect',async()=>{const {ac,nodes}=fake();let finish;ac.resume=()=>new Promise(r=>{finish=()=>{ac.state='running';r();};});const a=factory()(()=>ac),pending=a.enable(true);await a.enable(false);finish();await pending;assert.equal(ac.state,'suspended');assert.equal(a.status().on,false);ac.resume=()=>{ac.state='running';return Promise.resolve();};await a.enable(true);a.tick('foyer');assert.ok(a.status().voices>0);for(const o of nodes)o.onended();assert.equal(a.status().voices,0);});
test('changing Effects volume does not interrupt Music voices',async()=>{const {ac}=fake(),a=factory()(()=>ac);await a.enable(true);a.tick('foyer');const musicVoices=a.status().voices;a.effect('door');assert.ok(a.status().voices>musicVoices);a.setVolume('effects',0);assert.equal(a.status().voices,musicVoices);a.setVolume('music',0);assert.equal(a.status().voices,0);});
module.exports={factory,fake};
